In [2]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make('FrozenLake-v1', render_mode='ansi')

In [7]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(action_space_size)
print(state_space_size)

4
16


In [8]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [17]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()[0]
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])    # CHoose maximum from the Q table of that state.
        else:
            action = env.action_space.sample()      # Explore the environment.

        new_state, reward, done, truncated, info = env.step(action)

        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
        learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward 

        if done == True:     # Whether the agent reached a hole or goal. Check that the episode is over or not.
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000


# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Average reward per thousand episodes********

1000 :  0.05000000000000004
2000 :  0.18900000000000014
3000 :  0.4220000000000003
4000 :  0.5530000000000004
5000 :  0.6330000000000005
6000 :  0.6480000000000005
7000 :  0.6800000000000005
8000 :  0.6640000000000005
9000 :  0.6970000000000005
10000 :  0.6990000000000005


********Q-table********

[[0.55802059 0.50434119 0.49653464 0.49909845]
 [0.32257173 0.38531567 0.29224066 0.5002216 ]
 [0.43106013 0.41355503 0.42741241 0.45828128]
 [0.36510517 0.2955788  0.37222483 0.44411699]
 [0.58256214 0.36793436 0.4905443  0.30742906]
 [0.         0.         0.         0.        ]
 [0.18686314 0.17224892 0.3496052  0.12073813]
 [0.         0.         0.         0.        ]
 [0.37431593 0.45606249 0.30981002 0.63598602]
 [0.54978764 0.67077214 0.39128111 0.33056535]
 [0.59490789 0.43814356 0.44014386 0.27197988]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.59774765 0.55777749 0.78494877 