In [2]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make('FrozenLake-v1', render_mode='ansi')

In [7]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(action_space_size)
print(state_space_size)

4
16


In [8]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [23]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()[0]
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])    # CHoose maximum from the Q table of that state i.e it exploits the knowledge learnt.
        else:
            action = env.action_space.sample()      # Explore the environment i.e selects a random action from the action space when the
                                                    # agent chooses to explore the environment rather than exploit its current knowledge.

        new_state, reward, done, truncated, info = env.step(action)

        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
        learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward 

        if done == True:     # Whether the agent reached a hole or goal. Check that the episode is over or not.
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000


# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Average reward per thousand episodes********

1000 :  0.06600000000000004
2000 :  0.21400000000000016
3000 :  0.36100000000000027
4000 :  0.5760000000000004
5000 :  0.6400000000000005
6000 :  0.6720000000000005
7000 :  0.6690000000000005
8000 :  0.6810000000000005
9000 :  0.6750000000000005
10000 :  0.7090000000000005


********Q-table********

[[0.58907615 0.51878097 0.4982278  0.49495028]
 [0.31252369 0.30558794 0.4033032  0.51247005]
 [0.4158078  0.43960066 0.41762593 0.48091906]
 [0.34980756 0.27689529 0.33784659 0.45479009]
 [0.6159051  0.34264101 0.38773514 0.29570331]
 [0.         0.         0.         0.        ]
 [0.15669285 0.19245036 0.33709378 0.17001619]
 [0.         0.         0.         0.        ]
 [0.44977883 0.42149867 0.50959728 0.66798383]
 [0.43693892 0.71687761 0.49255703 0.42917216]
 [0.74090224 0.44513902 0.37776682 0.36849034]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.51581681 0.59766352 0.7957369 

In [ ]:
# means the agent was able to correctly navigate to the goal 70% of the time.

In [24]:
for episode in range(3):
    state = env.reset()[0]
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        print(env.render())
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])        # The agent selects an action based on the Q-table. It chooses the action with the highest Q-value for the current state.
        new_state, reward, done, truncated, info = env.step(action)
        if done:
            clear_output(wait=True)
            print(env.render())
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break

        state = new_state

env.close()



  (Down)
SFFF
FHFH
FFFH
HFFG

****You reached the goal!****


In [ ]:
#reference: deeplizard